{% set name = "dewret" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dewret-{{ version }}.tar.gz
  sha256: d0813cd53211cff4afb94e7580aea977c7d4a1fad4743dd6d6787444c9770a04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - hatchling <1.22
    - pip
  run:
    - python >=3.11
    - dask-core >=2022
    - pyyaml
    - attrs
    - click
    - setuptools >=65.5.1
    - numpy
    - sympy

test:
  imports:
    - dewret
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flaxandteal/dewret/
  summary: DEclarative Workflow REndering Tool
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Dewret allows certain workflows written in a dynamic
    style to be rendered to a static representation.
  doc_url: https://flaxandteal.github.io/dewret/
  dev_url: https://github.com/flaxandteal/dewret/

extra:
  recipe-maintainers:
    - philtweir
