{% set python_min = "3.11" %}
{% set name = "dewret" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dewret-{{ version }}.tar.gz
  sha256: 10218fa58a694364733a52aab937c79181875cfba19bd2444a2da75d5936fe43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling <1.22
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2022
    - pyyaml
    - attrs
    - click
    - setuptools >=65.5.1
    - numpy
    - sympy

test:
  imports:
    - dewret
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/flaxandteal/dewret/
  summary: DEclarative Workflow REndering Tool
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Dewret allows certain workflows written in a dynamic
    style to be rendered to a static representation.
  doc_url: https://flaxandteal.github.io/dewret/
  dev_url: https://github.com/flaxandteal/dewret/

extra:
  recipe-maintainers:
    - philtweir
